[bot]
name = "Hermes"
prefix = "^^"
owners = [1319707981377699920,
1425797581962874910]

[gateway]
shards = 1
reconnect_timeout = 30

[logging]
level = "info"
pretty = true

[lavalink]
host = "34.201.73.132"
port = 3333
password = "Ronlly"
https = false
