[bot]
name = "Hermes"
prefix = "^^"
owners = []

[gateway]
shards = 1
reconnect_timeout = 30

[logging]
level = "info"
pretty = true

[lavalink]
host = "54.159.193.249"
port = 3333
password = "Ronlly"
https = false
